#Create our first list (Artemis II Crew)
#Professor was using fruits (I just don't think that's aura)
artemiscrewList = ["Reid", "Victor", "Christina", "Jeremy", "Jenni"]
print(artemiscrewList)
#print specific item in the list
print(artemiscrewList[2])
#Update a position in the list
artemiscrewList[2] = "Stratt"
print(artemiscrewList)
howManyItems = len(artemiscrewList)
print(howManyItems)
print(len(artemiscrewList))
artemiscrewList.append("Ryland")
print(artemiscrewList)
artemiscrewList.append(67)
print(artemiscrewList)
print(artemiscrewList[1:4])
print(artemiscrewList[:3])
print(artemiscrewList[2:])
print(artemiscrewList[1:1])
print(artemiscrewList[1:2])
#insert into our list
artemiscrewList.insert(2, "Rocky")
print(artemiscrewList)
artemiscrewList.pop()
print(artemiscrewList)
artemiscrewList.insert(3, "Yunice")
print(artemiscrewList)
artemiscrewList.remove("Yunice")
print(artemiscrewList)
artemiscrewList.append("Ryland")
print(artemiscrewList)
artemiscrewList.remove("Ryland")
print(artemiscrewList)
